version: '3'
services:
  my-service:
    container_name: my-container-name
    image: my-image:latest
    ports:
      - "4000:4000"
      - '9229:9229'
    volumes:
      - .:/usr/src/app:cached
    command: ['npm', 'run', 'server:dev']
